sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- echo "This design module has no tests"
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET"
  -in deploy.enc -out deploy_key -d; fi
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: c2nMvUDT3ljEBZPL58cYhuzApBy6HeaGikXa+lJwT5Bou7Jj72Wsx+8WcMJi1RtLVf1R2oa8WUsnMvJgMExZcuGwfqLguaQ6bA5Zk5IXyPj8sqMI7HMr2BZVx+i+SKCkP0D8EtMDuxhIQtZtwVxkpTyU0WtCcCG62fvajMHn74aMKRg9MyNo7Ii1HAGb28Dz2Ga2Au93HR+MjgaOnlXYLymqRHRzoloNf3KZQq2s9M68JT2CMYCFHN/jafdSSdoTeWdMLy71T3sBPuH4CE00s4AXdYr8O2sd3UebYNfDp5872FLeZZEIaAsEB/njHnjWde6lr+KN62ZhjUM0IXTRih+uMejGVSimt3df1+bWJVMQCjgfn14sof7BHU9Pqs6Tm6ShRHpQikEw01r3/n380ydL223hJgbVdo7QXW7zqsmXP9JtJviQ6r3/Bq0NbjOHn1R5/y+jrRTFvtWdEZEic1VUAGQ9qCiwZh3c8ApDfzbxmZ238VHDcj0TgwbA8/rbUxlCz1GtEoYXPAuObLVc1qmkbcf+vVA2eTNAXCK+z/NQ9pcdYgNhDsu3uVTpMBG4bPz3r1cbA//7cXZuUqIQDIc625IrLwUDdySRpzFtyRvDZ4eR3K2u7IiXI9vAbVDR/ndLduTFgZOwy/TthSZpApo5rmAK3iqYB7Otv9BgcH0=
  - secure: Qr/pDMHF2K9g8C0TlRJE2FiTp3GlJDVngyUH8qu3O+r4igUa3MumKshtO5XbKBk7A4rBaVWPc8zQcIvkLWbhZETXyWZfgm7XKr52mTo1hDpTN2jZC7h8+jbnKtneFb0iQcEAltDeA5+vqBw8CivurGA8/AW5TVtwnBBBkRZZ54EfoeMFqP/suEpQxxtn3hvQFmTTNP5E+f6xlYfGM6xW1W++sWGjBebkUjj7Rt3YG6vUoqSQ9kqFN1YGypi3PXqCM6OTnCmOdEldfObQKg3LAblz/QF4RSBojHSxXuUczqdUZDs2drRDRaetDUM6DWLXWmfQrraVLYN3EJVEqffFFSlzhaciYa4oEdCgYrdMnRw4HE63PUyPtEohxEg2cuMcHuunt2dgb+B5moFEXz34r6TCHgVP3tH8Y0QbFsmhMCQcE/r1vItGq2Y1WWHP9OGjXXUaTVVUlS0ELvTk7XkSeo2zZa6YFSfRmG0fEFpDo+2jnzyd3RptnJoqgjSdmlwq7YZiTaynxCMC8UWoJsIdMJTHKbfAtjSvdKAHjgllUkgefZI4Zuh0MEdo5jg/RMDDBLYLBbcwpm15dVUEMJ243Fn9buNsia9T6M8lVtfi+czA/AcXjXlRsy3FTpfX1E9uhX7thHXVdOSBNJ3HVBEBWKz+CW4wfr1yteBp25I9Shs=
  - secure: Py3zA6NdrdXwWX4TrYume0V8H7V1zDXDboIZGxSsCO3aKiZ98mKFLxmKVmjS4GMQCxVe9Ur4rKSgTcf2Z41PjyYjfUqc/ZnSbI7zu8q0sjhTpvtvk+vdVrT4hgA4ffoYNI5WEJxBL5/FZEN0oaZUFXf8QDmTN2872CxLdVQaSk/KjkMQoKL7DdUDPJVfP/GJYSFFH4muQMEtQlmpNbP633muuY6+K6xPYLt4IatJJ7BrMxGsBRetF4mBmza8EWkYm2dQztLtjTKMjmol9BeueAuIVHH/Nj+F2dOywEYuXexNIiFrlud9al8N4QS6TqGHCLjhILzK5fupaYOHXD5Xob9B2Cur6211JmL8eUhnFB1ZXU8e5XBFhMHRmvvr5fL88ANKzJL2mjLDjWcXpQ03cAbZqJaRE6PUjhnsG4/fz3Wa6Kl7ZhwWD9SsSg/W6X8LmyK5QCrXllSvwfYA8pXUagdgUaUKJ6ulY1nAGCxP1L5SBMlZdpYi9TyvI6aj7lebf37WXNC8UPEFGChaa+g/26CGkkXBN1RSz5dRoSZcwHGYD5U5+BX/re5Jtx5F+6w8wyKQ6fXFakODcS8Lokn5Z9ate5SqeZirGMB9nWbCnSgbxDO9ncRHI+Bh8Gzb6NyRX7idMNPPrcxK/epjcNHU/0nxlQMSC/ila08gmjaCp1U=
  - secure: KiHSFL4h7+iHlUnzJiGOvFgBfnguXVIEGdhzuIn8AK/+rfwlqhFDnJ30uq030GSQrAsW/cL4onlivSl+ytrCeJ/o7lQk5PNFNHLLiPZRfgpt1ARzROToh06z2/n0fJNxJAlD9CrlCG+owKecKRPsdAJDG+K/DmCrVWKymqAbbu6YopRgPoixY8Sh/VR3IRMoXKXZs5Vg+WYaa7X6TmtrbrAZYgxeQaGLdsC3fENgm0rLZDJ5hto+YJzK4YJwLEHfcaILB4CZOvY7hb77yj9yB4jz3oCum7gq/KQDVY7hEC1I+nBShndsj3UcRizGgfzswkwvMGYV9SgVASnqveiLupnQ/g6qRf0YxHHceofl1Jy8Q2UkjzMp/wd42KU4E2A2DN2dvEB1M6J8GgYkYhrlYpb1CKF+06wX6sxzTo31Q3qFrPKOwApiRUdwUeXfEt0tOgdM4nuZnrE+NQSxftZTA+DqNSv+0+w2IouNpkcTNhLSB9DksFQOu7t56qgxN0mX8B2TBf4k6RVrSYFpkPeFmuT3ORNmatzV95s9l0g3fH6wEynvkVbVcfMDn5Y3t/4WCu0e32fPPp2GEf95TeRV1b7z2B+iRYZmxm2bNG2B5cSLYsTJtCPYu/JfbBpNJ3NT3IsoZhiILdsBoPzo70Otb3RZ2j22wJuM+sKgu/V3xZA=
